# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krewfile < Formula
  desc "Declarative krew plugin management"
  homepage "https://github.com/brumhard/krewfile"
  version "0.6.2"
  license "MIT"

  on_macos do
    url "https://github.com/brumhard/krewfile/releases/download/v0.6.2/krewfile_Darwin_all.tar.gz"
    sha256 "d72a112987f9ca23c9276e4ac0f8e8a31d2e03c75cdb02e7f8e5e284b0044bd4"

    def install
      bin.install "krewfile"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brumhard/krewfile/releases/download/v0.6.2/krewfile_Linux_x86_64.tar.gz"
        sha256 "75b6e5f242bf9b71618f77b97bed20127db3b0d16f7f7750ea580e47c09c1247"

        def install
          bin.install "krewfile"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brumhard/krewfile/releases/download/v0.6.2/krewfile_Linux_arm64.tar.gz"
        sha256 "bd4fea5c0c122c67b2c140620430797d0354bfa56421a0f026d919561d04bdee"

        def install
          bin.install "krewfile"
        end
      end
    end
  end
end
