# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krewfile < Formula
  desc "Declarative krew plugin management"
  homepage "https://github.com/brumhard/krewfile"
  version "0.6.3"
  license "MIT"

  on_macos do
    url "https://github.com/brumhard/krewfile/releases/download/v0.6.3/krewfile_Darwin_all.tar.gz"
    sha256 "5129be94a8d2284e3c7c5bd5d7237547bf2b8bf7ded9b8445a787c0910398493"

    def install
      bin.install "krewfile"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brumhard/krewfile/releases/download/v0.6.3/krewfile_Linux_x86_64.tar.gz"
        sha256 "48f8854ef4c9ffea9d5311c5adb4085ae0c7e782da8eeecd5a17cd71b493b6ac"

        def install
          bin.install "krewfile"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brumhard/krewfile/releases/download/v0.6.3/krewfile_Linux_arm64.tar.gz"
        sha256 "c20341ed668d50de6764a0dc3945afe2ba4625e88f49656874576b3b0b116f64"

        def install
          bin.install "krewfile"
        end
      end
    end
  end
end
