# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Masklint < Formula
  desc "Lint your mask targets."
  homepage "https://github.com/brumhard/masklint"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.1/masklint_darwin_amd64.tar.gz"
      sha256 "dbc81c97ac97b62f122a43269116503c61f19fe1c485adfde508d8999db19c41"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.1/masklint_darwin_arm64.tar.gz"
      sha256 "dfcd67868721d8c92ea219cc1b98a62c22d405d7f07bf3f51e098e6953225ece"

      def install
        bin.install "masklint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.1/masklint_linux_amd64.tar.gz"
      sha256 "7c90a6f31c2a3e1797337d07f5101bbf384b4ebc23cde9711c3ab42e77f2040e"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.1/masklint_linux_arm64.tar.gz"
      sha256 "6a008382cfda80bbfecdaac9e2bceaaa9dd26fab7eb3b3b6045f5ec52c73b7b6"

      def install
        bin.install "masklint"
      end
    end
  end
end
