# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Masklint < Formula
  desc "Lint your mask targets."
  homepage "https://github.com/brumhard/masklint"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.0/masklint_darwin_amd64.tar.gz"
      sha256 "8778d62cd45fa3e752831b066fe3ae5885e3f57f38be6a5c1b3297729fe31cf4"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.0/masklint_darwin_arm64.tar.gz"
      sha256 "e5d3e4ec21944aa775b474d73ae445839ebfed5bf0cba723813d3f23fcb4b9da"

      def install
        bin.install "masklint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.0/masklint_linux_amd64.tar.gz"
      sha256 "5ec96aa7a2120d5bdf69c1d2208eacde073516e60187ad2b62b018844a15003b"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/masklint/releases/download/v0.2.0/masklint_linux_arm64.tar.gz"
      sha256 "fb3ea7b5d49a7779ba9f5a55bb7dae421f3beb579145cd65ff2ef45d4a80b111"

      def install
        bin.install "masklint"
      end
    end
  end
end
