# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Masklint < Formula
  desc "Lint your mask targets."
  homepage "https://github.com/brumhard/masklint"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/masklint/releases/download/v0.3.0/masklint_darwin_arm64.tar.gz"
      sha256 "3621bf54f961d8f9786816c74c66423db34197b4395f07e8bfa506a51e73bf67"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.3.0/masklint_darwin_amd64.tar.gz"
      sha256 "a81d54d004a4f1b01117667d38d033939c833c27f9eb698d56aa3ffb82d9d1fc"

      def install
        bin.install "masklint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/masklint/releases/download/v0.3.0/masklint_linux_amd64.tar.gz"
      sha256 "b59ab0eb926127c8314420e2568c5795908e244561172b4dbfbb958a63e2da18"

      def install
        bin.install "masklint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/masklint/releases/download/v0.3.0/masklint_linux_arm64.tar.gz"
      sha256 "d77e6ac11a3284a9c954c636d4f31cb645dbf220d425f4d5fb84c94ea171d74c"

      def install
        bin.install "masklint"
      end
    end
  end
end
