# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reinlinsen < Formula
  desc "Inspect and dump OCI images"
  homepage "https://github.com/brumhard/reinlinsen"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.2/reinlinsen_darwin_amd64.tar.gz"
      sha256 "0f280bcf852d1b1a37ff239f2a764f63398f7639ce9ae7ae254be6743593871e"

      def install
        bin.install rl
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.2/reinlinsen_darwin_arm64.tar.gz"
      sha256 "a75f0185b1acc7738d854c1481bae7d457487eb79a1fd653299cbaa2be93ca25"

      def install
        bin.install rl
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.2/reinlinsen_linux_amd64.tar.gz"
      sha256 "4ac9d026e6feb68bb75c8a6a13a4ec7f61aeb525b0914111a0d2ec537a87302d"

      def install
        bin.install rl
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.2/reinlinsen_linux_arm64.tar.gz"
      sha256 "17b99d73a16ab1e046ce690cb262c1746a52cb7524f1af0b242b8ca4a1a9f009"

      def install
        bin.install rl
      end
    end
  end
end
