# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reinlinsen < Formula
  desc "Inspect and dump OCI images"
  homepage "https://github.com/brumhard/reinlinsen"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.7/reinlinsen_darwin_amd64.tar.gz"
      sha256 "2da31e94058a518d4c9bbf1a13e69452b86ad147651436015b1faff5dd071ffa"

      def install
        bin.install "rl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.7/reinlinsen_darwin_arm64.tar.gz"
      sha256 "44060ed01a7a694ee2424430630a83f3ac3479ec8d35dc87c10f356358d44427"

      def install
        bin.install "rl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.7/reinlinsen_linux_amd64.tar.gz"
      sha256 "3ee10c6d55e9e26ccd7db51eaee6cf0016c02f15ad4817e9246c1c6df5dfed51"

      def install
        bin.install "rl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.7/reinlinsen_linux_arm64.tar.gz"
      sha256 "3730abe3a198d65e1dcb687d3cacf6dcb31b6d4630dd36f41d6fd08b95390760"

      def install
        bin.install "rl"
      end
    end
  end
end
