# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reinlinsen < Formula
  desc "Inspect and dump OCI images"
  homepage "https://github.com/brumhard/reinlinsen"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.1/reinlinsen_darwin_amd64.tar.gz"
      sha256 "2dbf32ecf8422ddff99b69895a7f3467e9f740881a34fae40a5baf66373975f8"

      def install
        bin.install "rl_darwin_amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.1/reinlinsen_darwin_arm64.tar.gz"
      sha256 "08a75936c93062a247f6c7100f120484e13682c895f27011d92ad451c090c1a3"

      def install
        bin.install "rl_darwin_arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.1/reinlinsen_linux_amd64.tar.gz"
      sha256 "252b7afdadb2477d7e13033009e9bd0464e8d7d28daf86e0c9c5bd5105c9d709"

      def install
        bin.install "rl_linux_amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brumhard/reinlinsen/releases/download/v0.3.1/reinlinsen_linux_arm64.tar.gz"
      sha256 "592eebac386c72756c12d92a28782e700d6b0528eb8107f1987f4c91707598e4"

      def install
        bin.install "rl_linux_arm64"
      end
    end
  end
end
